### ISSUE TITLE
npm install v8flags Still Fails on Windows 

### ISSUE THREAD

**Issue by Techdoode** [tkellen/node-v8flags#9]
I have NodeJS version v0.10.33 installed on a Dell PC running Windows 7 Ultimate.  The npm version is 1.4.28.
When I issue npm install v8flags, I receive the following output from npm:

\
> v8flags@1.0.5 install c:\xampp\htdocs\responsive\node_modules\v8flags
> node fetch.js

npm ERR! v8flags@1.0.5 install: `node fetch.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8flags@1.0.5 install script.
npm ERR! This is most likely a problem with the v8flags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fetch.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8flags
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules
\\npm\\bin\\npm-cli.js" "install" "v8flags"
npm ERR! cwd c:\xampp\htdocs\responsive
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

I first encountered the problem attempting to install Gulp.  The install failed with messages similar to the above.  I then attempted to npm install v8flages, with the above results.

**Comment by tkellen** [comment]
Should be fixed in v8flags `2.0.0`.  Depends on gulpjs/gulp#11
